### ISSUE TITLE
回复列表的非常卡顿问题

### ISSUE THREAD

**Issue by zhy1905** [Naoki2015/CircleDemo#2]
用嵌套listview方式来做回复列表，当评论的数量非常多的时候就非常卡顿了，滑动起来像是被东西绊住一样

**Comment by zhy1905** [comment]
一般十条以上的评论就可以看到很卡了

**Comment by Naoki2015** [comment]
非常感谢你提出的问题，有时间我再优化下界面显示吧。

**Comment by szitguy** [comment]
回复列表用LinearLayout一条一条加不行么？

**Comment by nujnay** [comment]
@szitguy 感觉是需要看需求，评论的数量，但是使用listview感觉删除评论等操作比较方便吧

**Comment by Naoki2015** [comment]
@gdgm123 评论列表已优化，测试了十多条评论的情况效果还算可以。

**Comment by szitguy** [comment]
@Naoki2015 我看到貌似改成了LinearLayout实现？

**Comment by Naoki2015** [comment]
@szitguy 是的，用LinearLayout是比较合理的。效果我觉得还是比较明显的。
