### ISSUE TITLE
上拉加载框

### ISSUE THREAD

**Issue by JK520** [Naoki2015/CircleDemo#20]
您好，请问上拉加载那个加载框是不是改不了的？那个太简陋了，我想改成类似微信那样，但是那个类不能改动，麻烦指点一下

**Comment by Naoki2015** [comment]
嗯  晚点我会参考微信修改上拉加载框

**Comment by Naoki2015** [comment]
加载框已经修改了，具体布局可以设置布局app:layout_moreProgress="@layout/view_more_progress"
因为默认加载配置布局是wrap_content，所以你需要代码手动重新设置布局的宽recyclerView.getMoreProgressView().getLayoutParams().width = ViewGroup.LayoutParams.MATCH_PARENT;

**Comment by JK520** [comment]
太棒啦，这样就很灵活了，因为改不了，差点就放弃这个Demo了，非常感谢，值得学习！！！

**Comment by Naoki2015** [comment]
嗯  它还可以配置数据为空时的界面app:layout_empty="@layout/emptyview" 
SuperRecyclerView还是比较好用的，具体可以参考github和它的源码。
