### ISSUE TITLE
播放本地视频

### ISSUE THREAD

**Issue by JK520** [Naoki2015/CircleDemo#22]
请问播放视频不是这样写的吗？Glide.with(getContext()) .load(Uri.fromFile(new File(videoPath))).本人尝试之后没反应，想要替换掉控件又太麻烦了，希望作者提供下思路

**Comment by Naoki2015** [comment]
String filePath = "/storage/emulated/0/Pictures/example_video.mp4";
Glide  .with( context )
    .load( Uri.fromFile( new File( filePath ) ) )
    .into( imageViewGifAsBitmap );

你参考这个示例试试。

**Comment by JK520** [comment]
我就是网上参考这个也不行

**Comment by JK520** [comment]
你好，我把视频布局里边的自定义控件CircleVideoView换成了VideoView，属性都一样，为什么播放的时候控件宽度总是不能填充整个布局呢
