### ISSUE TITLE
9宫格图片点击的时候能否增加一个像微信那样的过渡效果？

### ISSUE THREAD

**Issue by Lsy1992** [Naoki2015/CircleDemo#24]

**Comment by nujnay** [comment]
不难做就是动画

**Comment by Caij** [comment]
同求这样的效果。最近同样想做这样的效果， 如果做接近的效果可以使用activity 转场动画， 但是activity 转场动画效果没微信效果那么好， 不够细腻会闪。
@yanjuncq  我尝试没有很好的方法解决， 不仅仅是简单的移动放大动画的。

**Comment by dingzhixiang** [comment]
http://blog.csdn.net/yyyangyy/article/details/61417930   可以参考这个
