### ISSUE TITLE
隐藏编辑框，手势冲突

### ISSUE THREAD

**Issue by LittlEyes** [Naoki2015/CircleDemo#27]
MainActivity 105行 这个地方应该复写recyclerview的onInterceptTouchEvent方法，而不是setOnTouchListener

**Comment by Naoki2015** [comment]
你说的这个冲突不知是否是你项目中因为某些需求有其他手势导致的冲突，还是demo中就存在这个冲突？
如果recyclerview的子view消费掉了touch事件是会导致键盘不会收回，那么复写onInterceptTouchEvent或者dispatchTouchEvent来隐藏键盘都可以解决这个问题。但是复写又要封装下会比较麻烦。如果demo中存在这个冲突，还请指点下是什么情况下能重现。

**Comment by Naoki2015** [comment]
我知道点击点赞列表或评论中的名字这种情况，事件是被消费掉了而不会传递到recyclerview的ontouch这，这样键盘就不会收回。
