### ISSUE TITLE
AppNoScrollerListView这个类作用是什么？怎么我断点进不去onTouch？

### ISSUE THREAD

**Issue by szitguy** [Naoki2015/CircleDemo#6]

**Comment by Naoki2015** [comment]
这个类是我项目中用到的，里面复写的OntouchEvent在这个demo里面没有什么用处，在这个demo中只是作为一个不能滑动的listview使用。

**Comment by szitguy** [comment]
嗯，确实，我把onTouch注释掉，也不影响程序运行。

主要是onMeasure那里使得listview不能滑动。
